package com.novalang.vm;

import com.novalang.instructions.Instruction;

import java.util.List;
import java.util.Map;

/**
 * Factory interface for creating the NovaVM instance.
 * This decouples the VM creation logic from the main application,
 * fulfilling the Dependency Injection (DI) requirement of the coursework.
 */
public interface NovaVMFactory {

    /**
     * Creates a new, initialized NovaVM instance ready to run a program.
     *
     * @param program The list of com.novalang.instructions generated by the Translator.
     * @param labels  The label-to-PC mapping.
     * @return An initialized NovaVM instance.
     */
    NovaVM create(List<Instruction> program, Map<String, Integer> labels);
}